version: "2.1"
services:
  pma:
    hostname: pma
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
    labels:
      - io.docksal.virtual-host=pma.${VIRTUAL_HOST}
  mail:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: mail
